/*
 * app_cfg.h
 *
 *  Created on: 01.06.2019
 *      Author: erics
 */

#ifndef APP_CFG_H_
#define APP_CFG_H_

/******************************************************************************
* Includes
*******************************************************************************/

/******************************************************************************
* Defines for internal messages
* The values below indicate the BASE index without the indication for an ACTION
* or EVENT. To convert between ACTION and EVENT you can use the msg_ACTION(index)
* or msg_EVENT(index) function.
* The BASE index is used to adjust or show ABSOLUT values. For DSP control there
* is also the possibility to adjust values RELATIVE. To do this you can simply
* use the BASE index + 1.
*******************************************************************************/
#define GENERATE_SW_VERSION(MAJOR, MINOR, REVISION, BUILD) ((MAJOR << 24) + (MINOR << 16) + (REVISION << 8) + (BUILD))

#define MCU_FW_VERSION	GENERATE_SW_VERSION(0, 0, 1, 0)
#define EE_FW_VERSION	GENERATE_SW_VERSION(0, 0, 1, 3)

/* Messages ORIGINs */
#define app_cfg_ONLY_INTERNAL_MSG_ORIGIN	0	/*Will not be send to any other interface*/
#define app_cfg_INTERNAL_MSG_ORIGIN			1	/*Is generated by internal events like switches*/
/* Messages TYPEs */
#define app_cfg_BTN_MSG			'B'
#define app_cfg_DMX_MSG			'D'
#define app_cfg_DMX_PRESET_MSG	'P'
/* Messages CTXs */
#define app_cfg_PHYSICAL_CONTROL_MSG_CTX	1	/*Must be send if a physical control should be changed by user software*/
/* General Defines */
#define app_cfg_NMBR_BTNS			5
#define app_cfg_NMBR_PRESETS		10
#define app_cfg_NMBR_TRANSITIONS	20

#define APP_CFG_IS_INDEX_IN_RANGE(IDX, START, END) ((((IDX) >= (START)) && ((IDX) < (END))) ? (true) : (false))
/******************************************************************************
* Interface/Command
*******************************************************************************/
/******************************************************************************
* LED Messages Index
*******************************************************************************/

/******************************************************************************
* Button Messages Index
*******************************************************************************/
/* Message */
#define app_cfg_btn_GPIO1_IDX	0
#define app_cfg_btn_GPIO2_IDX	1
#define app_cfg_btn_GPIO3_IDX	2
#define app_cfg_btn_GPIO4_IDX	3
#define app_cfg_btn_USER_IDX	4

#define app_cfg_btn_STAT_RELEASED		0
#define app_cfg_btn_STAT_PRESSED		1
#define app_cfg_btn_STAT_HOLD_SHORT		2
#define app_cfg_btn_STAT_HOLD_LONG		3

/* Times */
#define app_cfg_btn_TIME_DEBOUNCE 		4
#define app_cfg_btn_TIME_HOLD_SHORT 	2000/app_cfg_NMBR_BTNS
#define app_cfg_btn_TIME_HOLD_LONG 		4000/app_cfg_NMBR_BTNS
/******************************************************************************
* DMX Messages Index
*******************************************************************************/
/* Message Index */
#define app_cfg_dmx_CH_OFFSET_IDX	0

/* Values for dmx channel messages 0 - 255 */
/******************************************************************************
* DMX Preset Messages Index
*******************************************************************************/
/* Message Index */
#define app_cfg_dmx_preset_TRIGGER_PRESET_OFFSET_IDX	0
#define app_cfg_dmx_preset_TRIGGER_PRESET0_IDX			0
#define app_cfg_dmx_preset_TRIGGER_PRESET1_IDX			1
#define app_cfg_dmx_preset_TRIGGER_PRESET2_IDX			2
#define app_cfg_dmx_preset_TRIGGER_PRESET3_IDX			3
#define app_cfg_dmx_preset_TRIGGER_PRESET4_IDX			4

/* Values of trigger */
#define app_cfg_dmx_preset_TRIGGER_ENABLE	0x7FFF	/*0x7FFF*/
#define app_cfg_dmx_preset_TRIGGER_DISABLE	0x0000	/*0x7FFF*/
/******************************************************************************
* Footcontrol Messages Index
*******************************************************************************/
/* Message Index */

/* Values for presets messages 0 - 254 */
#define app_footcontrol_NO_PRESET 255
/******************************************************************************
* EEPROM Messages Index
*******************************************************************************/

/******************************************************************************
* MUTE Messages Index
*******************************************************************************/


#endif /* APP_CFG_H_ */
